//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AA01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AA01">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}RES" maxOccurs="2"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}OBJ" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}OBJ-m" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AA01", namespace = "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app", propOrder = {
    "res",
    "obj",
    "objm"
})
public class AA01
    extends IMObject
{

    @XmlElement(name = "RES", required = true)
    protected List<RefRSCRS> res;
    @XmlElement(name = "OBJ")
    protected List<OBJ> obj;
    @XmlElement(name = "OBJ-m")
    protected List<OBJM> objm;

    /**
     * Gets the value of the res property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the res property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefRSCRS }
     * 
     * 
     */
    public List<RefRSCRS> getRES() {
        if (res == null) {
            res = new ArrayList<RefRSCRS>();
        }
        return this.res;
    }

    /**
     * Gets the value of the obj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOBJ().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OBJ }
     * 
     * 
     */
    public List<OBJ> getOBJ() {
        if (obj == null) {
            obj = new ArrayList<OBJ>();
        }
        return this.obj;
    }

    /**
     * Gets the value of the objm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOBJM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OBJM }
     * 
     * 
     */
    public List<OBJM> getOBJM() {
        if (objm == null) {
            objm = new ArrayList<OBJM>();
        }
        return this.objm;
    }

}
