//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CI_Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CI_Address.deliveryPoint" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CI_Address.city" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="CI_Address.administrativeArea" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="CI_Address.postalCode" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="CI_Address.country" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="CI_Address.electronicMailAddress" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_Address", propOrder = {
    "ciAddressDeliveryPoint",
    "ciAddressCity",
    "ciAddressAdministrativeArea",
    "ciAddressPostalCode",
    "ciAddressCountry",
    "ciAddressElectronicMailAddress"
})
public class CIAddress {

    @XmlElement(name = "CI_Address.deliveryPoint", namespace = "")
    protected List<String> ciAddressDeliveryPoint;
    @XmlElement(name = "CI_Address.city", namespace = "")
    protected String ciAddressCity;
    @XmlElement(name = "CI_Address.administrativeArea", namespace = "")
    protected String ciAddressAdministrativeArea;
    @XmlElement(name = "CI_Address.postalCode", namespace = "")
    protected String ciAddressPostalCode;
    @XmlElement(name = "CI_Address.country", namespace = "")
    protected String ciAddressCountry;
    @XmlElement(name = "CI_Address.electronicMailAddress", namespace = "")
    protected List<String> ciAddressElectronicMailAddress;

    /**
     * Gets the value of the ciAddressDeliveryPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciAddressDeliveryPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCIAddressDeliveryPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCIAddressDeliveryPoint() {
        if (ciAddressDeliveryPoint == null) {
            ciAddressDeliveryPoint = new ArrayList<String>();
        }
        return this.ciAddressDeliveryPoint;
    }

    /**
     * Gets the value of the ciAddressCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIAddressCity() {
        return ciAddressCity;
    }

    /**
     * Sets the value of the ciAddressCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIAddressCity(String value) {
        this.ciAddressCity = value;
    }

    /**
     * Gets the value of the ciAddressAdministrativeArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIAddressAdministrativeArea() {
        return ciAddressAdministrativeArea;
    }

    /**
     * Sets the value of the ciAddressAdministrativeArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIAddressAdministrativeArea(String value) {
        this.ciAddressAdministrativeArea = value;
    }

    /**
     * Gets the value of the ciAddressPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIAddressPostalCode() {
        return ciAddressPostalCode;
    }

    /**
     * Sets the value of the ciAddressPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIAddressPostalCode(String value) {
        this.ciAddressPostalCode = value;
    }

    /**
     * Gets the value of the ciAddressCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIAddressCountry() {
        return ciAddressCountry;
    }

    /**
     * Sets the value of the ciAddressCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIAddressCountry(String value) {
        this.ciAddressCountry = value;
    }

    /**
     * Gets the value of the ciAddressElectronicMailAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciAddressElectronicMailAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCIAddressElectronicMailAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCIAddressElectronicMailAddress() {
        if (ciAddressElectronicMailAddress == null) {
            ciAddressElectronicMailAddress = new ArrayList<String>();
        }
        return this.ciAddressElectronicMailAddress;
    }

}
