//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CI_Contact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_Contact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CI_Contact.phone" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Telephone"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CI_Contact.address" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Address"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CI_Contact.onlineResource" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_OnlineResource"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CI_Contact.hoursOfService" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="CI_Contact.contactInstructions" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_Contact", propOrder = {
    "ciContactPhone",
    "ciContactAddress",
    "ciContactOnlineResource",
    "ciContactHoursOfService",
    "ciContactContactInstructions"
})
public class CIContact {

    @XmlElement(name = "CI_Contact.phone", namespace = "")
    protected CIContact.CIContactPhone ciContactPhone;
    @XmlElement(name = "CI_Contact.address", namespace = "")
    protected CIContact.CIContactAddress ciContactAddress;
    @XmlElement(name = "CI_Contact.onlineResource", namespace = "")
    protected CIContact.CIContactOnlineResource ciContactOnlineResource;
    @XmlElement(name = "CI_Contact.hoursOfService", namespace = "")
    protected String ciContactHoursOfService;
    @XmlElement(name = "CI_Contact.contactInstructions", namespace = "")
    protected String ciContactContactInstructions;

    /**
     * Gets the value of the ciContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link CIContact.CIContactPhone }
     *     
     */
    public CIContact.CIContactPhone getCIContactPhone() {
        return ciContactPhone;
    }

    /**
     * Sets the value of the ciContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIContact.CIContactPhone }
     *     
     */
    public void setCIContactPhone(CIContact.CIContactPhone value) {
        this.ciContactPhone = value;
    }

    /**
     * Gets the value of the ciContactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link CIContact.CIContactAddress }
     *     
     */
    public CIContact.CIContactAddress getCIContactAddress() {
        return ciContactAddress;
    }

    /**
     * Sets the value of the ciContactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIContact.CIContactAddress }
     *     
     */
    public void setCIContactAddress(CIContact.CIContactAddress value) {
        this.ciContactAddress = value;
    }

    /**
     * Gets the value of the ciContactOnlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link CIContact.CIContactOnlineResource }
     *     
     */
    public CIContact.CIContactOnlineResource getCIContactOnlineResource() {
        return ciContactOnlineResource;
    }

    /**
     * Sets the value of the ciContactOnlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIContact.CIContactOnlineResource }
     *     
     */
    public void setCIContactOnlineResource(CIContact.CIContactOnlineResource value) {
        this.ciContactOnlineResource = value;
    }

    /**
     * Gets the value of the ciContactHoursOfService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIContactHoursOfService() {
        return ciContactHoursOfService;
    }

    /**
     * Sets the value of the ciContactHoursOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIContactHoursOfService(String value) {
        this.ciContactHoursOfService = value;
    }

    /**
     * Gets the value of the ciContactContactInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIContactContactInstructions() {
        return ciContactContactInstructions;
    }

    /**
     * Sets the value of the ciContactContactInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIContactContactInstructions(String value) {
        this.ciContactContactInstructions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Address"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ciAddress"
    })
    public static class CIContactAddress {

        @XmlElement(name = "CI_Address", required = true)
        protected CIAddress ciAddress;

        /**
         * Gets the value of the ciAddress property.
         * 
         * @return
         *     possible object is
         *     {@link CIAddress }
         *     
         */
        public CIAddress getCIAddress() {
            return ciAddress;
        }

        /**
         * Sets the value of the ciAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link CIAddress }
         *     
         */
        public void setCIAddress(CIAddress value) {
            this.ciAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_OnlineResource"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ciOnlineResource"
    })
    public static class CIContactOnlineResource {

        @XmlElement(name = "CI_OnlineResource", required = true)
        protected CIOnlineResource ciOnlineResource;

        /**
         * Gets the value of the ciOnlineResource property.
         * 
         * @return
         *     possible object is
         *     {@link CIOnlineResource }
         *     
         */
        public CIOnlineResource getCIOnlineResource() {
            return ciOnlineResource;
        }

        /**
         * Sets the value of the ciOnlineResource property.
         * 
         * @param value
         *     allowed object is
         *     {@link CIOnlineResource }
         *     
         */
        public void setCIOnlineResource(CIOnlineResource value) {
            this.ciOnlineResource = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Telephone"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ciTelephone"
    })
    public static class CIContactPhone {

        @XmlElement(name = "CI_Telephone", required = true)
        protected CITelephone ciTelephone;

        /**
         * Gets the value of the ciTelephone property.
         * 
         * @return
         *     possible object is
         *     {@link CITelephone }
         *     
         */
        public CITelephone getCITelephone() {
            return ciTelephone;
        }

        /**
         * Sets the value of the ciTelephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link CITelephone }
         *     
         */
        public void setCITelephone(CITelephone value) {
            this.ciTelephone = value;
        }

    }

}
