//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CI_Date complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_Date">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CI_Date.date" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Date"/>
 *         &lt;element name="CI_Date.dateType" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_DateTypeCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_Date", propOrder = {
    "ciDateDate",
    "ciDateDateType"
})
public class CIDate {

    @XmlElement(name = "CI_Date.date", namespace = "", required = true)
    protected XMLGregorianCalendar ciDateDate;
    @XmlElement(name = "CI_Date.dateType", namespace = "", required = true)
    protected String ciDateDateType;

    /**
     * Gets the value of the ciDateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCIDateDate() {
        return ciDateDate;
    }

    /**
     * Sets the value of the ciDateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCIDateDate(XMLGregorianCalendar value) {
        this.ciDateDate = value;
    }

    /**
     * Gets the value of the ciDateDateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIDateDateType() {
        return ciDateDateType;
    }

    /**
     * Sets the value of the ciDateDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIDateDateType(String value) {
        this.ciDateDateType = value;
    }

}
