//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CI_OnlineResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_OnlineResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CI_OnlineResource.linkage" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}URI"/>
 *         &lt;element name="CI_OnlineResource.description" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_OnlineResource", propOrder = {
    "ciOnlineResourceLinkage",
    "ciOnlineResourceDescription"
})
public class CIOnlineResource {

    @XmlElement(name = "CI_OnlineResource.linkage", namespace = "", required = true)
    protected String ciOnlineResourceLinkage;
    @XmlElement(name = "CI_OnlineResource.description", namespace = "")
    protected String ciOnlineResourceDescription;

    /**
     * Gets the value of the ciOnlineResourceLinkage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIOnlineResourceLinkage() {
        return ciOnlineResourceLinkage;
    }

    /**
     * Sets the value of the ciOnlineResourceLinkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIOnlineResourceLinkage(String value) {
        this.ciOnlineResourceLinkage = value;
    }

    /**
     * Gets the value of the ciOnlineResourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIOnlineResourceDescription() {
        return ciOnlineResourceDescription;
    }

    /**
     * Sets the value of the ciOnlineResourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIOnlineResourceDescription(String value) {
        this.ciOnlineResourceDescription = value;
    }

}
