//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CI_Telephone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_Telephone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CI_Telephone.voice" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CI_Telephone.facsimile" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_Telephone", propOrder = {
    "ciTelephoneVoice",
    "ciTelephoneFacsimile"
})
public class CITelephone {

    @XmlElement(name = "CI_Telephone.voice", namespace = "")
    protected List<String> ciTelephoneVoice;
    @XmlElement(name = "CI_Telephone.facsimile", namespace = "")
    protected List<String> ciTelephoneFacsimile;

    /**
     * Gets the value of the ciTelephoneVoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciTelephoneVoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCITelephoneVoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCITelephoneVoice() {
        if (ciTelephoneVoice == null) {
            ciTelephoneVoice = new ArrayList<String>();
        }
        return this.ciTelephoneVoice;
    }

    /**
     * Gets the value of the ciTelephoneFacsimile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciTelephoneFacsimile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCITelephoneFacsimile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCITelephoneFacsimile() {
        if (ciTelephoneFacsimile == null) {
            ciTelephoneFacsimile = new ArrayList<String>();
        }
        return this.ciTelephoneFacsimile;
    }

}
