//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_Coverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_Coverage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_Coverage.domainExtent" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_Coverage.rangeType"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_Coverage.CRS"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_Coverage", propOrder = {
    "cvCoverageDomainExtent",
    "cvCoverageRangeType",
    "cvCoverageCRS"
})
@XmlSeeAlso({
    CVDiscreteCoverage.class,
    CVContinuousCoverage.class
})
public abstract class CVCoverage
    extends IMObject
{

    @XmlElement(name = "CV_Coverage.domainExtent", required = true)
    protected List<EXExtent> cvCoverageDomainExtent;
    @XmlElement(name = "CV_Coverage.rangeType", required = true)
    protected RefRecordType cvCoverageRangeType;
    @XmlElement(name = "CV_Coverage.CRS", required = true)
    protected RefRSCRS cvCoverageCRS;

    /**
     * Gets the value of the cvCoverageDomainExtent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvCoverageDomainExtent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCVCoverageDomainExtent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXExtent }
     * 
     * 
     */
    public List<EXExtent> getCVCoverageDomainExtent() {
        if (cvCoverageDomainExtent == null) {
            cvCoverageDomainExtent = new ArrayList<EXExtent>();
        }
        return this.cvCoverageDomainExtent;
    }

    /**
     * Gets the value of the cvCoverageRangeType property.
     * 
     * @return
     *     possible object is
     *     {@link RefRecordType }
     *     
     */
    public RefRecordType getCVCoverageRangeType() {
        return cvCoverageRangeType;
    }

    /**
     * Sets the value of the cvCoverageRangeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRecordType }
     *     
     */
    public void setCVCoverageRangeType(RefRecordType value) {
        this.cvCoverageRangeType = value;
    }

    /**
     * Gets the value of the cvCoverageCRS property.
     * 
     * @return
     *     possible object is
     *     {@link RefRSCRS }
     *     
     */
    public RefRSCRS getCVCoverageCRS() {
        return cvCoverageCRS;
    }

    /**
     * Sets the value of the cvCoverageCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRSCRS }
     *     
     */
    public void setCVCoverageCRS(RefRSCRS value) {
        this.cvCoverageCRS = value;
    }

}
