//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_DiscreteCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_DiscreteCoverage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_Coverage">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_DiscreteCoverage.element" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_DiscreteCoverage", propOrder = {
    "cvDiscreteCoverageElement"
})
@XmlSeeAlso({
    CVDiscreteCurveCoverage.class,
    CVDiscreteSurfaceCoverage.class,
    CVDiscretePointCoverage.class
})
public class CVDiscreteCoverage
    extends CVCoverage
{

    @XmlElement(name = "CV_DiscreteCoverage.element", required = true)
    protected List<CVDiscreteCoverageElement> cvDiscreteCoverageElement;

    /**
     * Gets the value of the cvDiscreteCoverageElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvDiscreteCoverageElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCVDiscreteCoverageElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVDiscreteCoverageElement }
     * 
     * 
     */
    public List<CVDiscreteCoverageElement> getCVDiscreteCoverageElement() {
        if (cvDiscreteCoverageElement == null) {
            cvDiscreteCoverageElement = new ArrayList<CVDiscreteCoverageElement>();
        }
        return this.cvDiscreteCoverageElement;
    }

}
