//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_GeometryValuePair complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_GeometryValuePair">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_GeometryValuePair.geometry"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_GeometryValuePair.value"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_GeometryValuePair", propOrder = {
    "cvGeometryValuePairGeometry",
    "cvGeometryValuePairValue"
})
@XmlSeeAlso({
    CVPointValuePair.class,
    CVCurveValuePair.class,
    CVSurfaceValuePair.class
})
public class CVGeometryValuePair
    extends IMObject
{

    @XmlElement(name = "CV_GeometryValuePair.geometry", required = true)
    protected RefGMObject cvGeometryValuePairGeometry;
    @XmlElement(name = "CV_GeometryValuePair.value", required = true)
    protected RefRecord cvGeometryValuePairValue;

    /**
     * Gets the value of the cvGeometryValuePairGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMObject }
     *     
     */
    public RefGMObject getCVGeometryValuePairGeometry() {
        return cvGeometryValuePairGeometry;
    }

    /**
     * Sets the value of the cvGeometryValuePairGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMObject }
     *     
     */
    public void setCVGeometryValuePairGeometry(RefGMObject value) {
        this.cvGeometryValuePairGeometry = value;
    }

    /**
     * Gets the value of the cvGeometryValuePairValue property.
     * 
     * @return
     *     possible object is
     *     {@link RefRecord }
     *     
     */
    public RefRecord getCVGeometryValuePairValue() {
        return cvGeometryValuePairValue;
    }

    /**
     * Sets the value of the cvGeometryValuePairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRecord }
     *     
     */
    public void setCVGeometryValuePairValue(RefRecord value) {
        this.cvGeometryValuePairValue = value;
    }

}
