//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_ThiessenValuePolygon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_ThiessenValuePolygon">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ValueObject">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ThiessenValuePolygon.geometry"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ThiessenValuePolygon.controlValue"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_ThiessenValuePolygon", propOrder = {
    "cvThiessenValuePolygonGeometry",
    "cvThiessenValuePolygonControlValue"
})
public class CVThiessenValuePolygon
    extends CVValueObject
{

    @XmlElement(name = "CV_ThiessenValuePolygon.geometry", required = true)
    protected RefGMPolygon cvThiessenValuePolygonGeometry;
    @XmlElement(name = "CV_ThiessenValuePolygon.controlValue", required = true)
    protected CVThiessenValuePolygonControlValue cvThiessenValuePolygonControlValue;

    /**
     * Gets the value of the cvThiessenValuePolygonGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMPolygon }
     *     
     */
    public RefGMPolygon getCVThiessenValuePolygonGeometry() {
        return cvThiessenValuePolygonGeometry;
    }

    /**
     * Sets the value of the cvThiessenValuePolygonGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMPolygon }
     *     
     */
    public void setCVThiessenValuePolygonGeometry(RefGMPolygon value) {
        this.cvThiessenValuePolygonGeometry = value;
    }

    /**
     * Gets the value of the cvThiessenValuePolygonControlValue property.
     * 
     * @return
     *     possible object is
     *     {@link CVThiessenValuePolygonControlValue }
     *     
     */
    public CVThiessenValuePolygonControlValue getCVThiessenValuePolygonControlValue() {
        return cvThiessenValuePolygonControlValue;
    }

    /**
     * Sets the value of the cvThiessenValuePolygonControlValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CVThiessenValuePolygonControlValue }
     *     
     */
    public void setCVThiessenValuePolygonControlValue(CVThiessenValuePolygonControlValue value) {
        this.cvThiessenValuePolygonControlValue = value;
    }

}
