//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_TINCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_TINCoverage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ContinuousCoverage">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_TINCoverage.geometry"/>
 *         &lt;element name="CV_TINCoverage.element" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ValueTriangle" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_TINCoverage", propOrder = {
    "cvtinCoverageGeometry",
    "cvtinCoverageElement"
})
public class CVTINCoverage
    extends CVContinuousCoverage
{

    @XmlElement(name = "CV_TINCoverage.geometry", required = true)
    protected RefGMTin cvtinCoverageGeometry;
    @XmlElement(name = "CV_TINCoverage.element", namespace = "", required = true)
    protected List<CVValueTriangle> cvtinCoverageElement;

    /**
     * Gets the value of the cvtinCoverageGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMTin }
     *     
     */
    public RefGMTin getCVTINCoverageGeometry() {
        return cvtinCoverageGeometry;
    }

    /**
     * Sets the value of the cvtinCoverageGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMTin }
     *     
     */
    public void setCVTINCoverageGeometry(RefGMTin value) {
        this.cvtinCoverageGeometry = value;
    }

    /**
     * Gets the value of the cvtinCoverageElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvtinCoverageElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCVTINCoverageElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVValueTriangle }
     * 
     * 
     */
    public List<CVValueTriangle> getCVTINCoverageElement() {
        if (cvtinCoverageElement == null) {
            cvtinCoverageElement = new ArrayList<CVValueTriangle>();
        }
        return this.cvtinCoverageElement;
    }

}
