//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CV_ValueTriangle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV_ValueTriangle">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ValueObject">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ValueTriangle.geometry"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CV_ValueTriangle.controlValue" maxOccurs="3" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV_ValueTriangle", propOrder = {
    "cvValueTriangleGeometry",
    "cvValueTriangleControlValue"
})
public class CVValueTriangle
    extends CVValueObject
{

    @XmlElement(name = "CV_ValueTriangle.geometry", required = true)
    protected RefGMTriangle cvValueTriangleGeometry;
    @XmlElement(name = "CV_ValueTriangle.controlValue", required = true)
    protected List<CVValueTriangleControlValue> cvValueTriangleControlValue;

    /**
     * Gets the value of the cvValueTriangleGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMTriangle }
     *     
     */
    public RefGMTriangle getCVValueTriangleGeometry() {
        return cvValueTriangleGeometry;
    }

    /**
     * Sets the value of the cvValueTriangleGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMTriangle }
     *     
     */
    public void setCVValueTriangleGeometry(RefGMTriangle value) {
        this.cvValueTriangleGeometry = value;
    }

    /**
     * Gets the value of the cvValueTriangleControlValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvValueTriangleControlValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCVValueTriangleControlValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVValueTriangleControlValue }
     * 
     * 
     */
    public List<CVValueTriangleControlValue> getCVValueTriangleControlValue() {
        if (cvValueTriangleControlValue == null) {
            cvValueTriangleControlValue = new ArrayList<CVValueTriangleControlValue>();
        }
        return this.cvValueTriangleControlValue;
    }

}
