//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dictionary_AttributeName_TypeName_ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dictionary_AttributeName_TypeName_">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="AttributeName" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString"/>
 *         &lt;element name="TypeName" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dictionary_AttributeName_TypeName_", propOrder = {
    "attributeNameAndTypeName"
})
public class DictionaryAttributeNameTypeName {

    @XmlElementRefs({
        @XmlElementRef(name = "TypeName", type = JAXBElement.class),
        @XmlElementRef(name = "AttributeName", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> attributeNameAndTypeName;

    /**
     * Gets the value of the attributeNameAndTypeName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeNameAndTypeName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeNameAndTypeName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getAttributeNameAndTypeName() {
        if (attributeNameAndTypeName == null) {
            attributeNameAndTypeName = new ArrayList<JAXBElement<String>>();
        }
        return this.attributeNameAndTypeName;
    }

}
