//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * type of “S“¹
 * 
 * <p>Java class for EB01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EB01">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}AA02">
 *       &lt;sequence>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}LOC"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}RAC"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}INT"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}LIN"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}OPC"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EB01", namespace = "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app", propOrder = {
    "loc",
    "rac",
    "_int",
    "lin",
    "opc"
})
@XmlSeeAlso({
    EB03 .class,
    EB02 .class
})
public class EB01
    extends AA02
{

    @XmlElement(name = "LOC", required = true)
    protected RefGMCurve loc;
    @XmlElement(name = "RAC", required = true)
    protected CodeType rac;
    @XmlElement(name = "INT", required = true)
    protected CodeType _int;
    @XmlElement(name = "LIN", required = true)
    protected String lin;
    @XmlElement(name = "OPC", required = true)
    protected String opc;

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMCurve }
     *     
     */
    public RefGMCurve getLOC() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMCurve }
     *     
     */
    public void setLOC(RefGMCurve value) {
        this.loc = value;
    }

    /**
     * Gets the value of the rac property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getRAC() {
        return rac;
    }

    /**
     * Sets the value of the rac property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setRAC(CodeType value) {
        this.rac = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getINT() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setINT(CodeType value) {
        this._int = value;
    }

    /**
     * Gets the value of the lin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIN() {
        return lin;
    }

    /**
     * Sets the value of the lin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIN(String value) {
        this.lin = value;
    }

    /**
     * Gets the value of the opc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPC() {
        return opc;
    }

    /**
     * Sets the value of the opc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPC(String value) {
        this.opc = value;
    }

}
