//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * type of “S“¹‹æŠÔ
 * 
 * <p>Java class for EB02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EB02">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}EB01">
 *       &lt;sequence>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}RAS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EB02", namespace = "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app", propOrder = {
    "ras"
})
public class EB02
    extends EB01
{

    @XmlElement(name = "RAS")
    protected List<RefEB03> ras;

    /**
     * Gets the value of the ras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRAS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefEB03 }
     * 
     * 
     */
    public List<RefEB03> getRAS() {
        if (ras == null) {
            ras = new ArrayList<RefEB03>();
        }
        return this.ras;
    }

}
