//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * type of ‰w
 * 
 * <p>Java class for EB03 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EB03">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}EB01">
 *       &lt;sequence>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}STN"/>
 *         &lt;element ref="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}SRS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EB03", namespace = "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app", propOrder = {
    "stn",
    "srs"
})
public class EB03
    extends EB01
{

    @XmlElement(name = "STN", required = true)
    protected String stn;
    @XmlElement(name = "SRS")
    protected List<RefEB02> srs;

    /**
     * Gets the value of the stn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTN() {
        return stn;
    }

    /**
     * Sets the value of the stn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTN(String value) {
        this.stn = value;
    }

    /**
     * Gets the value of the srs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the srs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefEB02 }
     * 
     * 
     */
    public List<RefEB02> getSRS() {
        if (srs == null) {
            srs = new ArrayList<RefEB02>();
        }
        return this.srs;
    }

}
