//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExchangeMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExchangeMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasetCitation" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Citation"/>
 *         &lt;element name="metadataCitation" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Citation" minOccurs="0"/>
 *         &lt;element name="applicationSchemaCitation" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CI_Citation" minOccurs="0"/>
 *         &lt;element name="encodingRule" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EncodingRule"/>
 *         &lt;element name="codeLists" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CodeListExtraction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeMetadata", propOrder = {
    "datasetCitation",
    "metadataCitation",
    "applicationSchemaCitation",
    "encodingRule",
    "codeLists"
})
public class ExchangeMetadata {

    @XmlElement(namespace = "", required = true)
    protected CICitation datasetCitation;
    @XmlElement(namespace = "")
    protected CICitation metadataCitation;
    @XmlElement(namespace = "")
    protected CICitation applicationSchemaCitation;
    @XmlElement(namespace = "", required = true)
    protected EncodingRule encodingRule;
    @XmlElement(namespace = "")
    protected List<CodeListExtraction> codeLists;

    /**
     * Gets the value of the datasetCitation property.
     * 
     * @return
     *     possible object is
     *     {@link CICitation }
     *     
     */
    public CICitation getDatasetCitation() {
        return datasetCitation;
    }

    /**
     * Sets the value of the datasetCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICitation }
     *     
     */
    public void setDatasetCitation(CICitation value) {
        this.datasetCitation = value;
    }

    /**
     * Gets the value of the metadataCitation property.
     * 
     * @return
     *     possible object is
     *     {@link CICitation }
     *     
     */
    public CICitation getMetadataCitation() {
        return metadataCitation;
    }

    /**
     * Sets the value of the metadataCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICitation }
     *     
     */
    public void setMetadataCitation(CICitation value) {
        this.metadataCitation = value;
    }

    /**
     * Gets the value of the applicationSchemaCitation property.
     * 
     * @return
     *     possible object is
     *     {@link CICitation }
     *     
     */
    public CICitation getApplicationSchemaCitation() {
        return applicationSchemaCitation;
    }

    /**
     * Sets the value of the applicationSchemaCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICitation }
     *     
     */
    public void setApplicationSchemaCitation(CICitation value) {
        this.applicationSchemaCitation = value;
    }

    /**
     * Gets the value of the encodingRule property.
     * 
     * @return
     *     possible object is
     *     {@link EncodingRule }
     *     
     */
    public EncodingRule getEncodingRule() {
        return encodingRule;
    }

    /**
     * Sets the value of the encodingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodingRule }
     *     
     */
    public void setEncodingRule(EncodingRule value) {
        this.encodingRule = value;
    }

    /**
     * Gets the value of the codeLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codeLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodeLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeListExtraction }
     * 
     * 
     */
    public List<CodeListExtraction> getCodeLists() {
        if (codeLists == null) {
            codeLists = new ArrayList<CodeListExtraction>();
        }
        return this.codeLists;
    }

}
