//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_CoordinateBoundingBox complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_CoordinateBoundingBox">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_CoordinateBoundingBox.westBoundCoordinate"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_CoordinateBoundingBox.eastBoundCoordinate"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_CoordinateBoundingBox.southBoundCoordinate"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_CoordinateBoundingBox.northBoundCoordinate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_CoordinateBoundingBox", propOrder = {
    "exCoordinateBoundingBoxWestBoundCoordinate",
    "exCoordinateBoundingBoxEastBoundCoordinate",
    "exCoordinateBoundingBoxSouthBoundCoordinate",
    "exCoordinateBoundingBoxNorthBoundCoordinate"
})
public class EXCoordinateBoundingBox
    extends EXGeographicExtent
{

    @XmlElement(name = "EX_CoordinateBoundingBox.westBoundCoordinate", required = true)
    protected BigDecimal exCoordinateBoundingBoxWestBoundCoordinate;
    @XmlElement(name = "EX_CoordinateBoundingBox.eastBoundCoordinate", required = true)
    protected BigDecimal exCoordinateBoundingBoxEastBoundCoordinate;
    @XmlElement(name = "EX_CoordinateBoundingBox.southBoundCoordinate", required = true)
    protected BigDecimal exCoordinateBoundingBoxSouthBoundCoordinate;
    @XmlElement(name = "EX_CoordinateBoundingBox.northBoundCoordinate", required = true)
    protected BigDecimal exCoordinateBoundingBoxNorthBoundCoordinate;

    /**
     * Gets the value of the exCoordinateBoundingBoxWestBoundCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCoordinateBoundingBoxWestBoundCoordinate() {
        return exCoordinateBoundingBoxWestBoundCoordinate;
    }

    /**
     * Sets the value of the exCoordinateBoundingBoxWestBoundCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCoordinateBoundingBoxWestBoundCoordinate(BigDecimal value) {
        this.exCoordinateBoundingBoxWestBoundCoordinate = value;
    }

    /**
     * Gets the value of the exCoordinateBoundingBoxEastBoundCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCoordinateBoundingBoxEastBoundCoordinate() {
        return exCoordinateBoundingBoxEastBoundCoordinate;
    }

    /**
     * Sets the value of the exCoordinateBoundingBoxEastBoundCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCoordinateBoundingBoxEastBoundCoordinate(BigDecimal value) {
        this.exCoordinateBoundingBoxEastBoundCoordinate = value;
    }

    /**
     * Gets the value of the exCoordinateBoundingBoxSouthBoundCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCoordinateBoundingBoxSouthBoundCoordinate() {
        return exCoordinateBoundingBoxSouthBoundCoordinate;
    }

    /**
     * Sets the value of the exCoordinateBoundingBoxSouthBoundCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCoordinateBoundingBoxSouthBoundCoordinate(BigDecimal value) {
        this.exCoordinateBoundingBoxSouthBoundCoordinate = value;
    }

    /**
     * Gets the value of the exCoordinateBoundingBoxNorthBoundCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXCoordinateBoundingBoxNorthBoundCoordinate() {
        return exCoordinateBoundingBoxNorthBoundCoordinate;
    }

    /**
     * Sets the value of the exCoordinateBoundingBoxNorthBoundCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXCoordinateBoundingBoxNorthBoundCoordinate(BigDecimal value) {
        this.exCoordinateBoundingBoxNorthBoundCoordinate = value;
    }

}
