//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_Extent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_Extent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EX_Extent.description" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" minOccurs="0"/>
 *         &lt;element name="EX_Extent.geographicElement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EX_Extent.temporalElement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_TemporalExtent" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EX_Extent.verticalElement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_Extent", propOrder = {
    "exExtentDescription",
    "exExtentGeographicElement",
    "exExtentTemporalElement",
    "exExtentVerticalElement"
})
public class EXExtent {

    @XmlElement(name = "EX_Extent.description", namespace = "")
    protected String exExtentDescription;
    @XmlElement(name = "EX_Extent.geographicElement", namespace = "")
    protected List<EXExtent.EXExtentGeographicElement> exExtentGeographicElement;
    @XmlElement(name = "EX_Extent.temporalElement", namespace = "")
    protected List<EXExtent.EXExtentTemporalElement> exExtentTemporalElement;
    @XmlElement(name = "EX_Extent.verticalElement", namespace = "")
    protected List<EXExtent.EXExtentVerticalElement> exExtentVerticalElement;

    /**
     * Gets the value of the exExtentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXExtentDescription() {
        return exExtentDescription;
    }

    /**
     * Sets the value of the exExtentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXExtentDescription(String value) {
        this.exExtentDescription = value;
    }

    /**
     * Gets the value of the exExtentGeographicElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exExtentGeographicElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXExtentGeographicElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXExtent.EXExtentGeographicElement }
     * 
     * 
     */
    public List<EXExtent.EXExtentGeographicElement> getEXExtentGeographicElement() {
        if (exExtentGeographicElement == null) {
            exExtentGeographicElement = new ArrayList<EXExtent.EXExtentGeographicElement>();
        }
        return this.exExtentGeographicElement;
    }

    /**
     * Gets the value of the exExtentTemporalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exExtentTemporalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXExtentTemporalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXExtent.EXExtentTemporalElement }
     * 
     * 
     */
    public List<EXExtent.EXExtentTemporalElement> getEXExtentTemporalElement() {
        if (exExtentTemporalElement == null) {
            exExtentTemporalElement = new ArrayList<EXExtent.EXExtentTemporalElement>();
        }
        return this.exExtentTemporalElement;
    }

    /**
     * Gets the value of the exExtentVerticalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exExtentVerticalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXExtentVerticalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXExtent.EXExtentVerticalElement }
     * 
     * 
     */
    public List<EXExtent.EXExtentVerticalElement> getEXExtentVerticalElement() {
        if (exExtentVerticalElement == null) {
            exExtentVerticalElement = new ArrayList<EXExtent.EXExtentVerticalElement>();
        }
        return this.exExtentVerticalElement;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exGeographicExtent"
    })
    public static class EXExtentGeographicElement {

        @XmlElementRef(name = "EX_GeographicExtent", namespace = "http://www.gsi.go.jp/GIS/jpgis/standardSchemas", type = JAXBElement.class)
        protected JAXBElement<? extends EXGeographicExtent> exGeographicExtent;
        @XmlAttribute
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected java.lang.Object idref;
        @XmlAttribute
        protected String uuidref;
        @XmlAttribute
        protected String uriref;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String type;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String role;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String arcrole;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String title;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String show;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String actuate;

        /**
         * Gets the value of the exGeographicExtent property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link EXGeographicBoundingBox }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXGeographicExtent }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXCoordinateBoundingBox }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXBoundingPolygon }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXGeographicDescription }{@code >}
         *     
         */
        public JAXBElement<? extends EXGeographicExtent> getEXGeographicExtent() {
            return exGeographicExtent;
        }

        /**
         * Sets the value of the exGeographicExtent property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link EXGeographicBoundingBox }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXGeographicExtent }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXCoordinateBoundingBox }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXBoundingPolygon }{@code >}
         *     {@link JAXBElement }{@code <}{@link EXGeographicDescription }{@code >}
         *     
         */
        public void setEXGeographicExtent(JAXBElement<? extends EXGeographicExtent> value) {
            this.exGeographicExtent = ((JAXBElement<? extends EXGeographicExtent> ) value);
        }

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getIdref() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setIdref(java.lang.Object value) {
            this.idref = value;
        }

        /**
         * Gets the value of the uuidref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUuidref() {
            return uuidref;
        }

        /**
         * Sets the value of the uuidref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUuidref(String value) {
            this.uuidref = value;
        }

        /**
         * Gets the value of the uriref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUriref() {
            return uriref;
        }

        /**
         * Sets the value of the uriref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUriref(String value) {
            this.uriref = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            if (type == null) {
                return "simple";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

        /**
         * Gets the value of the arcrole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArcrole() {
            return arcrole;
        }

        /**
         * Sets the value of the arcrole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArcrole(String value) {
            this.arcrole = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the show property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShow() {
            return show;
        }

        /**
         * Sets the value of the show property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShow(String value) {
            this.show = value;
        }

        /**
         * Gets the value of the actuate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActuate() {
            return actuate;
        }

        /**
         * Sets the value of the actuate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActuate(String value) {
            this.actuate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_TemporalExtent" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exTemporalExtent"
    })
    public static class EXExtentTemporalElement {

        @XmlElement(name = "EX_TemporalExtent")
        protected EXTemporalExtent exTemporalExtent;
        @XmlAttribute
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected java.lang.Object idref;
        @XmlAttribute
        protected String uuidref;
        @XmlAttribute
        protected String uriref;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String type;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String role;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String arcrole;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String title;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String show;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String actuate;

        /**
         * Gets the value of the exTemporalExtent property.
         * 
         * @return
         *     possible object is
         *     {@link EXTemporalExtent }
         *     
         */
        public EXTemporalExtent getEXTemporalExtent() {
            return exTemporalExtent;
        }

        /**
         * Sets the value of the exTemporalExtent property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXTemporalExtent }
         *     
         */
        public void setEXTemporalExtent(EXTemporalExtent value) {
            this.exTemporalExtent = value;
        }

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getIdref() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setIdref(java.lang.Object value) {
            this.idref = value;
        }

        /**
         * Gets the value of the uuidref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUuidref() {
            return uuidref;
        }

        /**
         * Sets the value of the uuidref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUuidref(String value) {
            this.uuidref = value;
        }

        /**
         * Gets the value of the uriref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUriref() {
            return uriref;
        }

        /**
         * Sets the value of the uriref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUriref(String value) {
            this.uriref = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            if (type == null) {
                return "simple";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

        /**
         * Gets the value of the arcrole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArcrole() {
            return arcrole;
        }

        /**
         * Sets the value of the arcrole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArcrole(String value) {
            this.arcrole = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the show property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShow() {
            return show;
        }

        /**
         * Sets the value of the show property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShow(String value) {
            this.show = value;
        }

        /**
         * Gets the value of the actuate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActuate() {
            return actuate;
        }

        /**
         * Sets the value of the actuate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActuate(String value) {
            this.actuate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_ObjectReference"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exVerticalExtent"
    })
    public static class EXExtentVerticalElement {

        @XmlElement(name = "EX_VerticalExtent")
        protected EXVerticalExtent exVerticalExtent;
        @XmlAttribute
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected java.lang.Object idref;
        @XmlAttribute
        protected String uuidref;
        @XmlAttribute
        protected String uriref;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String type;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String role;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String arcrole;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String title;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String show;
        @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
        protected String actuate;

        /**
         * Gets the value of the exVerticalExtent property.
         * 
         * @return
         *     possible object is
         *     {@link EXVerticalExtent }
         *     
         */
        public EXVerticalExtent getEXVerticalExtent() {
            return exVerticalExtent;
        }

        /**
         * Sets the value of the exVerticalExtent property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXVerticalExtent }
         *     
         */
        public void setEXVerticalExtent(EXVerticalExtent value) {
            this.exVerticalExtent = value;
        }

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getIdref() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setIdref(java.lang.Object value) {
            this.idref = value;
        }

        /**
         * Gets the value of the uuidref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUuidref() {
            return uuidref;
        }

        /**
         * Sets the value of the uuidref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUuidref(String value) {
            this.uuidref = value;
        }

        /**
         * Gets the value of the uriref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUriref() {
            return uriref;
        }

        /**
         * Sets the value of the uriref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUriref(String value) {
            this.uriref = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            if (type == null) {
                return "simple";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

        /**
         * Gets the value of the arcrole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArcrole() {
            return arcrole;
        }

        /**
         * Sets the value of the arcrole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArcrole(String value) {
            this.arcrole = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the show property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShow() {
            return show;
        }

        /**
         * Sets the value of the show property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShow(String value) {
            this.show = value;
        }

        /**
         * Gets the value of the actuate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActuate() {
            return actuate;
        }

        /**
         * Sets the value of the actuate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActuate(String value) {
            this.actuate = value;
        }

    }

}
