//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_GeographicBoundingBox complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_GeographicBoundingBox">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicBoundingBox.westBoundLongitude"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicBoundingBox.eastBoundLongitude"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicBoundingBox.southBoundLatitude"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicBoundingBox.northBoundLatitude"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_GeographicBoundingBox", propOrder = {
    "exGeographicBoundingBoxWestBoundLongitude",
    "exGeographicBoundingBoxEastBoundLongitude",
    "exGeographicBoundingBoxSouthBoundLatitude",
    "exGeographicBoundingBoxNorthBoundLatitude"
})
public class EXGeographicBoundingBox
    extends EXGeographicExtent
{

    @XmlElement(name = "EX_GeographicBoundingBox.westBoundLongitude", required = true)
    protected Measure exGeographicBoundingBoxWestBoundLongitude;
    @XmlElement(name = "EX_GeographicBoundingBox.eastBoundLongitude", required = true)
    protected Measure exGeographicBoundingBoxEastBoundLongitude;
    @XmlElement(name = "EX_GeographicBoundingBox.southBoundLatitude", required = true)
    protected Measure exGeographicBoundingBoxSouthBoundLatitude;
    @XmlElement(name = "EX_GeographicBoundingBox.northBoundLatitude", required = true)
    protected Measure exGeographicBoundingBoxNorthBoundLatitude;

    /**
     * Gets the value of the exGeographicBoundingBoxWestBoundLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getEXGeographicBoundingBoxWestBoundLongitude() {
        return exGeographicBoundingBoxWestBoundLongitude;
    }

    /**
     * Sets the value of the exGeographicBoundingBoxWestBoundLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setEXGeographicBoundingBoxWestBoundLongitude(Measure value) {
        this.exGeographicBoundingBoxWestBoundLongitude = value;
    }

    /**
     * Gets the value of the exGeographicBoundingBoxEastBoundLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getEXGeographicBoundingBoxEastBoundLongitude() {
        return exGeographicBoundingBoxEastBoundLongitude;
    }

    /**
     * Sets the value of the exGeographicBoundingBoxEastBoundLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setEXGeographicBoundingBoxEastBoundLongitude(Measure value) {
        this.exGeographicBoundingBoxEastBoundLongitude = value;
    }

    /**
     * Gets the value of the exGeographicBoundingBoxSouthBoundLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getEXGeographicBoundingBoxSouthBoundLatitude() {
        return exGeographicBoundingBoxSouthBoundLatitude;
    }

    /**
     * Sets the value of the exGeographicBoundingBoxSouthBoundLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setEXGeographicBoundingBoxSouthBoundLatitude(Measure value) {
        this.exGeographicBoundingBoxSouthBoundLatitude = value;
    }

    /**
     * Gets the value of the exGeographicBoundingBoxNorthBoundLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getEXGeographicBoundingBoxNorthBoundLatitude() {
        return exGeographicBoundingBoxNorthBoundLatitude;
    }

    /**
     * Sets the value of the exGeographicBoundingBoxNorthBoundLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setEXGeographicBoundingBoxNorthBoundLatitude(Measure value) {
        this.exGeographicBoundingBoxNorthBoundLatitude = value;
    }

}
