//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_GeographicExtent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_GeographicExtent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent.extentTypeCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent.extentReferenceSystem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_GeographicExtent", propOrder = {
    "exGeographicExtentExtentTypeCode",
    "exGeographicExtentExtentReferenceSystem"
})
@XmlSeeAlso({
    EXGeographicBoundingBox.class,
    EXBoundingPolygon.class,
    EXGeographicDescription.class,
    EXCoordinateBoundingBox.class
})
public abstract class EXGeographicExtent
    extends IMObject
{

    @XmlElement(name = "EX_GeographicExtent.extentTypeCode")
    protected Boolean exGeographicExtentExtentTypeCode;
    @XmlElement(name = "EX_GeographicExtent.extentReferenceSystem")
    protected EXGeographicExtentExtentReferenceSystem exGeographicExtentExtentReferenceSystem;

    /**
     * Gets the value of the exGeographicExtentExtentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEXGeographicExtentExtentTypeCode() {
        return exGeographicExtentExtentTypeCode;
    }

    /**
     * Sets the value of the exGeographicExtentExtentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEXGeographicExtentExtentTypeCode(Boolean value) {
        this.exGeographicExtentExtentTypeCode = value;
    }

    /**
     * Gets the value of the exGeographicExtentExtentReferenceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link EXGeographicExtentExtentReferenceSystem }
     *     
     */
    public EXGeographicExtentExtentReferenceSystem getEXGeographicExtentExtentReferenceSystem() {
        return exGeographicExtentExtentReferenceSystem;
    }

    /**
     * Sets the value of the exGeographicExtentExtentReferenceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXGeographicExtentExtentReferenceSystem }
     *     
     */
    public void setEXGeographicExtentExtentReferenceSystem(EXGeographicExtentExtentReferenceSystem value) {
        this.exGeographicExtentExtentReferenceSystem = value;
    }

}
