//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_GeographicDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_GeographicDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicExtent">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_GeographicDescription.geographicIdentifier"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_GeographicDescription", propOrder = {
    "exGeographicDescriptionGeographicIdentifier"
})
public class EXGeographicDescription
    extends EXGeographicExtent
{

    @XmlElement(name = "EX_GeographicDescription.geographicIdentifier", required = true)
    protected EXGeographicDescriptionGeographicIdentifier exGeographicDescriptionGeographicIdentifier;

    /**
     * Gets the value of the exGeographicDescriptionGeographicIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link EXGeographicDescriptionGeographicIdentifier }
     *     
     */
    public EXGeographicDescriptionGeographicIdentifier getEXGeographicDescriptionGeographicIdentifier() {
        return exGeographicDescriptionGeographicIdentifier;
    }

    /**
     * Sets the value of the exGeographicDescriptionGeographicIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXGeographicDescriptionGeographicIdentifier }
     *     
     */
    public void setEXGeographicDescriptionGeographicIdentifier(EXGeographicDescriptionGeographicIdentifier value) {
        this.exGeographicDescriptionGeographicIdentifier = value;
    }

}
