//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_TemporalExtent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_TemporalExtent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_TemporalExtent.extent"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_TemporalExtent", propOrder = {
    "exTemporalExtentExtent"
})
public class EXTemporalExtent
    extends IMObject
{

    @XmlElement(name = "EX_TemporalExtent.extent", required = true)
    protected RefTMPrimitive exTemporalExtentExtent;

    /**
     * Gets the value of the exTemporalExtentExtent property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMPrimitive }
     *     
     */
    public RefTMPrimitive getEXTemporalExtentExtent() {
        return exTemporalExtentExtent;
    }

    /**
     * Sets the value of the exTemporalExtentExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMPrimitive }
     *     
     */
    public void setEXTemporalExtentExtent(RefTMPrimitive value) {
        this.exTemporalExtentExtent = value;
    }

}
