//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EX_VerticalExtent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_VerticalExtent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent.minimumValue"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent.maximumValue"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent.unitOfMeasure"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}EX_VerticalExtent.verticalDatum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_VerticalExtent", propOrder = {
    "exVerticalExtentMinimumValue",
    "exVerticalExtentMaximumValue",
    "exVerticalExtentUnitOfMeasure",
    "exVerticalExtentVerticalDatum"
})
public class EXVerticalExtent
    extends IMObject
{

    @XmlElement(name = "EX_VerticalExtent.minimumValue", required = true)
    protected BigDecimal exVerticalExtentMinimumValue;
    @XmlElement(name = "EX_VerticalExtent.maximumValue", required = true)
    protected BigDecimal exVerticalExtentMaximumValue;
    @XmlElement(name = "EX_VerticalExtent.unitOfMeasure", required = true)
    protected UnitOfMeasure exVerticalExtentUnitOfMeasure;
    @XmlElement(name = "EX_VerticalExtent.verticalDatum", required = true)
    protected RefSCVerticalDatum exVerticalExtentVerticalDatum;

    /**
     * Gets the value of the exVerticalExtentMinimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXVerticalExtentMinimumValue() {
        return exVerticalExtentMinimumValue;
    }

    /**
     * Sets the value of the exVerticalExtentMinimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXVerticalExtentMinimumValue(BigDecimal value) {
        this.exVerticalExtentMinimumValue = value;
    }

    /**
     * Gets the value of the exVerticalExtentMaximumValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXVerticalExtentMaximumValue() {
        return exVerticalExtentMaximumValue;
    }

    /**
     * Sets the value of the exVerticalExtentMaximumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXVerticalExtentMaximumValue(BigDecimal value) {
        this.exVerticalExtentMaximumValue = value;
    }

    /**
     * Gets the value of the exVerticalExtentUnitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfMeasure }
     *     
     */
    public UnitOfMeasure getEXVerticalExtentUnitOfMeasure() {
        return exVerticalExtentUnitOfMeasure;
    }

    /**
     * Sets the value of the exVerticalExtentUnitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfMeasure }
     *     
     */
    public void setEXVerticalExtentUnitOfMeasure(UnitOfMeasure value) {
        this.exVerticalExtentUnitOfMeasure = value;
    }

    /**
     * Gets the value of the exVerticalExtentVerticalDatum property.
     * 
     * @return
     *     possible object is
     *     {@link RefSCVerticalDatum }
     *     
     */
    public RefSCVerticalDatum getEXVerticalExtentVerticalDatum() {
        return exVerticalExtentVerticalDatum;
    }

    /**
     * Sets the value of the exVerticalExtentVerticalDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefSCVerticalDatum }
     *     
     */
    public void setEXVerticalExtentVerticalDatum(RefSCVerticalDatum value) {
        this.exVerticalExtentVerticalDatum = value;
    }

}
