//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exchangeMetadata" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}ExchangeMetadata" minOccurs="0"/>
 *         &lt;element name="dataset" type="{http://nlftp.mlit.go.jp/ksj/schemas/ksj-app}Dataset" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString" fixed="1.0" />
 *       &lt;attribute name="timeStamp" use="required" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}DateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeMetadata",
    "dataset"
})
@XmlRootElement(name = "GI", namespace = "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app")
public class GI {

    @XmlElement(namespace = "")
    protected ExchangeMetadata exchangeMetadata;
    @XmlElement(namespace = "")
    protected Dataset dataset;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar timeStamp;

    /**
     * Gets the value of the exchangeMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeMetadata }
     *     
     */
    public ExchangeMetadata getExchangeMetadata() {
        return exchangeMetadata;
    }

    /**
     * Sets the value of the exchangeMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeMetadata }
     *     
     */
    public void setExchangeMetadata(ExchangeMetadata value) {
        this.exchangeMetadata = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link Dataset }
     *     
     */
    public Dataset getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataset }
     *     
     */
    public void setDataset(Dataset value) {
        this.dataset = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

}
