//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_CurveInterpolation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GM_CurveInterpolation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="linear"/>
 *     &lt;enumeration value="circlerArc3Points"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GM_CurveInterpolation")
@XmlEnum
public enum GMCurveInterpolation {

    @XmlEnumValue("linear")
    LINEAR("linear"),
    @XmlEnumValue("circlerArc3Points")
    CIRCLER_ARC_3_POINTS("circlerArc3Points");
    private final String value;

    GMCurveInterpolation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GMCurveInterpolation fromValue(String v) {
        for (GMCurveInterpolation c: GMCurveInterpolation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
