//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_LineString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_LineString">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_CurveSegments">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_LineString.controlPoint"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_LineString", propOrder = {
    "gmLineStringControlPoint"
})
public class GMLineString
    extends GMCurveSegments
{

    @XmlElement(name = "GM_LineString.controlPoint", required = true)
    protected GMLineStringControlPoint gmLineStringControlPoint;

    /**
     * Gets the value of the gmLineStringControlPoint property.
     * 
     * @return
     *     possible object is
     *     {@link GMLineStringControlPoint }
     *     
     */
    public GMLineStringControlPoint getGMLineStringControlPoint() {
        return gmLineStringControlPoint;
    }

    /**
     * Sets the value of the gmLineStringControlPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMLineStringControlPoint }
     *     
     */
    public void setGMLineStringControlPoint(GMLineStringControlPoint value) {
        this.gmLineStringControlPoint = value;
    }

}
