//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_OrientablePrimitive complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_OrientablePrimitive">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Primitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_OrientablePrimitive.orientation"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_OrientablePrimitive.primitive"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_OrientablePrimitive", propOrder = {
    "gmOrientablePrimitiveOrientation",
    "gmOrientablePrimitivePrimitive"
})
@XmlSeeAlso({
    GMOrientableCurve.class,
    GMOrientableSurface.class
})
public abstract class GMOrientablePrimitive
    extends GMPrimitive
{

    @XmlElement(name = "GM_OrientablePrimitive.orientation", required = true)
    protected String gmOrientablePrimitiveOrientation;
    @XmlElement(name = "GM_OrientablePrimitive.primitive", required = true)
    protected RefGMPrimitive gmOrientablePrimitivePrimitive;

    /**
     * Gets the value of the gmOrientablePrimitiveOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGMOrientablePrimitiveOrientation() {
        return gmOrientablePrimitiveOrientation;
    }

    /**
     * Sets the value of the gmOrientablePrimitiveOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGMOrientablePrimitiveOrientation(String value) {
        this.gmOrientablePrimitiveOrientation = value;
    }

    /**
     * Gets the value of the gmOrientablePrimitivePrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link RefGMPrimitive }
     *     
     */
    public RefGMPrimitive getGMOrientablePrimitivePrimitive() {
        return gmOrientablePrimitivePrimitive;
    }

    /**
     * Sets the value of the gmOrientablePrimitivePrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefGMPrimitive }
     *     
     */
    public void setGMOrientablePrimitivePrimitive(RefGMPrimitive value) {
        this.gmOrientablePrimitivePrimitive = value;
    }

}
