//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_Position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_Position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Position.direct"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Position.indirect"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_Position", propOrder = {
    "gmPositionDirect",
    "gmPositionIndirect"
})
public class GMPosition {

    @XmlElement(name = "GM_Position.direct")
    protected DirectPosition gmPositionDirect;
    @XmlElement(name = "GM_Position.indirect")
    protected GMPointRef gmPositionIndirect;

    /**
     * Gets the value of the gmPositionDirect property.
     * 
     * @return
     *     possible object is
     *     {@link DirectPosition }
     *     
     */
    public DirectPosition getGMPositionDirect() {
        return gmPositionDirect;
    }

    /**
     * Sets the value of the gmPositionDirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectPosition }
     *     
     */
    public void setGMPositionDirect(DirectPosition value) {
        this.gmPositionDirect = value;
    }

    /**
     * Gets the value of the gmPositionIndirect property.
     * 
     * @return
     *     possible object is
     *     {@link GMPointRef }
     *     
     */
    public GMPointRef getGMPositionIndirect() {
        return gmPositionIndirect;
    }

    /**
     * Sets the value of the gmPositionIndirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMPointRef }
     *     
     */
    public void setGMPositionIndirect(GMPointRef value) {
        this.gmPositionIndirect = value;
    }

}
