//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_PointArray complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_PointArray">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GM_PointArray.column" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Position" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_PointArray", propOrder = {
    "gmPointArrayColumn"
})
public class GMPointArray {

    @XmlElement(name = "GM_PointArray.column", namespace = "", required = true)
    protected List<GMPosition> gmPointArrayColumn;

    /**
     * Gets the value of the gmPointArrayColumn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gmPointArrayColumn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGMPointArrayColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GMPosition }
     * 
     * 
     */
    public List<GMPosition> getGMPointArrayColumn() {
        if (gmPointArrayColumn == null) {
            gmPointArrayColumn = new ArrayList<GMPosition>();
        }
        return this.gmPointArrayColumn;
    }

}
