//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_SurfaceBoundary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_SurfaceBoundary">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_PrimitiveBoundary">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_SurfaceBoundary.exterior" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_SurfaceBoundary.interior" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_SurfaceBoundary", propOrder = {
    "gmSurfaceBoundaryExterior",
    "gmSurfaceBoundaryInterior"
})
public class GMSurfaceBoundary
    extends GMPrimitiveBoundary
{

    @XmlElement(name = "GM_SurfaceBoundary.exterior")
    protected GMSurfaceBoundaryExterior gmSurfaceBoundaryExterior;
    @XmlElement(name = "GM_SurfaceBoundary.interior")
    protected List<GMSurfaceBoundaryInterior> gmSurfaceBoundaryInterior;

    /**
     * Gets the value of the gmSurfaceBoundaryExterior property.
     * 
     * @return
     *     possible object is
     *     {@link GMSurfaceBoundaryExterior }
     *     
     */
    public GMSurfaceBoundaryExterior getGMSurfaceBoundaryExterior() {
        return gmSurfaceBoundaryExterior;
    }

    /**
     * Sets the value of the gmSurfaceBoundaryExterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMSurfaceBoundaryExterior }
     *     
     */
    public void setGMSurfaceBoundaryExterior(GMSurfaceBoundaryExterior value) {
        this.gmSurfaceBoundaryExterior = value;
    }

    /**
     * Gets the value of the gmSurfaceBoundaryInterior property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gmSurfaceBoundaryInterior property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGMSurfaceBoundaryInterior().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GMSurfaceBoundaryInterior }
     * 
     * 
     */
    public List<GMSurfaceBoundaryInterior> getGMSurfaceBoundaryInterior() {
        if (gmSurfaceBoundaryInterior == null) {
            gmSurfaceBoundaryInterior = new ArrayList<GMSurfaceBoundaryInterior>();
        }
        return this.gmSurfaceBoundaryInterior;
    }

}
