//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_SurfacePatchs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_SurfacePatchs">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_SurfacePatch.interpolation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_SurfacePatchs", propOrder = {
    "gmSurfacePatchInterpolation"
})
@XmlSeeAlso({
    GMPolygon.class
})
public abstract class GMSurfacePatchs
    extends IMObject
{

    @XmlElement(name = "GM_SurfacePatch.interpolation", required = true)
    protected GMSurfaceInterpolation gmSurfacePatchInterpolation;

    /**
     * Gets the value of the gmSurfacePatchInterpolation property.
     * 
     * @return
     *     possible object is
     *     {@link GMSurfaceInterpolation }
     *     
     */
    public GMSurfaceInterpolation getGMSurfacePatchInterpolation() {
        return gmSurfacePatchInterpolation;
    }

    /**
     * Sets the value of the gmSurfacePatchInterpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMSurfaceInterpolation }
     *     
     */
    public void setGMSurfacePatchInterpolation(GMSurfaceInterpolation value) {
        this.gmSurfacePatchInterpolation = value;
    }

}
