//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GM_Tin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GM_Tin">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_TriangulatedSurface">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Tin.stopLines"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Tin.breakLines"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Tin.maxLength"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Tin.controlPoint" maxOccurs="unbounded" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GM_Tin", propOrder = {
    "gmTinStopLines",
    "gmTinBreakLines",
    "gmTinMaxLength",
    "gmTinControlPoint"
})
public class GMTin
    extends GMTriangulatedSurface
{

    @XmlElement(name = "GM_Tin.stopLines", required = true)
    protected SetGMLineString gmTinStopLines;
    @XmlElement(name = "GM_Tin.breakLines", required = true)
    protected SetGMLineString gmTinBreakLines;
    @XmlElement(name = "GM_Tin.maxLength", required = true)
    protected Measure gmTinMaxLength;
    @XmlElement(name = "GM_Tin.controlPoint", required = true)
    protected List<GMPosition> gmTinControlPoint;

    /**
     * Gets the value of the gmTinStopLines property.
     * 
     * @return
     *     possible object is
     *     {@link SetGMLineString }
     *     
     */
    public SetGMLineString getGMTinStopLines() {
        return gmTinStopLines;
    }

    /**
     * Sets the value of the gmTinStopLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetGMLineString }
     *     
     */
    public void setGMTinStopLines(SetGMLineString value) {
        this.gmTinStopLines = value;
    }

    /**
     * Gets the value of the gmTinBreakLines property.
     * 
     * @return
     *     possible object is
     *     {@link SetGMLineString }
     *     
     */
    public SetGMLineString getGMTinBreakLines() {
        return gmTinBreakLines;
    }

    /**
     * Sets the value of the gmTinBreakLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetGMLineString }
     *     
     */
    public void setGMTinBreakLines(SetGMLineString value) {
        this.gmTinBreakLines = value;
    }

    /**
     * Gets the value of the gmTinMaxLength property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getGMTinMaxLength() {
        return gmTinMaxLength;
    }

    /**
     * Sets the value of the gmTinMaxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setGMTinMaxLength(Measure value) {
        this.gmTinMaxLength = value;
    }

    /**
     * Gets the value of the gmTinControlPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gmTinControlPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGMTinControlPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GMPosition }
     * 
     * 
     */
    public List<GMPosition> getGMTinControlPoint() {
        if (gmTinControlPoint == null) {
            gmTinControlPoint = new ArrayList<GMPosition>();
        }
        return this.gmTinControlPoint;
    }

}
