//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JP_Cell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JP_Cell">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Cell.gridCoord"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Cell.value"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Cell.scanDirection"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Cell.element" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JP_Cell", propOrder = {
    "jpCellGridCoord",
    "jpCellValue",
    "jpCellScanDirection",
    "jpCellElement"
})
public class JPCell
    extends IMObject
{

    @XmlElement(name = "JP_Cell.gridCoord", required = true)
    protected JPCoordinate jpCellGridCoord;
    @XmlElement(name = "JP_Cell.value", required = true)
    protected RefRecord jpCellValue;
    @XmlList
    @XmlElement(name = "JP_Cell.scanDirection", required = true)
    protected List<String> jpCellScanDirection;
    @XmlElement(name = "JP_Cell.element")
    protected List<JPCellElement> jpCellElement;

    /**
     * Gets the value of the jpCellGridCoord property.
     * 
     * @return
     *     possible object is
     *     {@link JPCoordinate }
     *     
     */
    public JPCoordinate getJPCellGridCoord() {
        return jpCellGridCoord;
    }

    /**
     * Sets the value of the jpCellGridCoord property.
     * 
     * @param value
     *     allowed object is
     *     {@link JPCoordinate }
     *     
     */
    public void setJPCellGridCoord(JPCoordinate value) {
        this.jpCellGridCoord = value;
    }

    /**
     * Gets the value of the jpCellValue property.
     * 
     * @return
     *     possible object is
     *     {@link RefRecord }
     *     
     */
    public RefRecord getJPCellValue() {
        return jpCellValue;
    }

    /**
     * Sets the value of the jpCellValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRecord }
     *     
     */
    public void setJPCellValue(RefRecord value) {
        this.jpCellValue = value;
    }

    /**
     * Gets the value of the jpCellScanDirection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jpCellScanDirection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJPCellScanDirection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getJPCellScanDirection() {
        if (jpCellScanDirection == null) {
            jpCellScanDirection = new ArrayList<String>();
        }
        return this.jpCellScanDirection;
    }

    /**
     * Gets the value of the jpCellElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jpCellElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJPCellElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JPCellElement }
     * 
     * 
     */
    public List<JPCellElement> getJPCellElement() {
        if (jpCellElement == null) {
            jpCellElement = new ArrayList<JPCellElement>();
        }
        return this.jpCellElement;
    }

}
