//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JP_Coordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JP_Coordinate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="JP_Coordinate.grid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_GridCoordinate"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="JP_Coordinate.mesh">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_MeshCode"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JP_Coordinate", propOrder = {
    "jpCoordinateGrid",
    "jpCoordinateMesh"
})
public class JPCoordinate {

    @XmlElement(name = "JP_Coordinate.grid", namespace = "")
    protected JPCoordinate.JPCoordinateGrid jpCoordinateGrid;
    @XmlElement(name = "JP_Coordinate.mesh", namespace = "")
    protected JPCoordinate.JPCoordinateMesh jpCoordinateMesh;

    /**
     * Gets the value of the jpCoordinateGrid property.
     * 
     * @return
     *     possible object is
     *     {@link JPCoordinate.JPCoordinateGrid }
     *     
     */
    public JPCoordinate.JPCoordinateGrid getJPCoordinateGrid() {
        return jpCoordinateGrid;
    }

    /**
     * Sets the value of the jpCoordinateGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JPCoordinate.JPCoordinateGrid }
     *     
     */
    public void setJPCoordinateGrid(JPCoordinate.JPCoordinateGrid value) {
        this.jpCoordinateGrid = value;
    }

    /**
     * Gets the value of the jpCoordinateMesh property.
     * 
     * @return
     *     possible object is
     *     {@link JPCoordinate.JPCoordinateMesh }
     *     
     */
    public JPCoordinate.JPCoordinateMesh getJPCoordinateMesh() {
        return jpCoordinateMesh;
    }

    /**
     * Sets the value of the jpCoordinateMesh property.
     * 
     * @param value
     *     allowed object is
     *     {@link JPCoordinate.JPCoordinateMesh }
     *     
     */
    public void setJPCoordinateMesh(JPCoordinate.JPCoordinateMesh value) {
        this.jpCoordinateMesh = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_GridCoordinate"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jpGridCoordinate"
    })
    public static class JPCoordinateGrid {

        @XmlElement(name = "JP_GridCoordinate", required = true)
        protected JPGridCoordinate jpGridCoordinate;

        /**
         * Gets the value of the jpGridCoordinate property.
         * 
         * @return
         *     possible object is
         *     {@link JPGridCoordinate }
         *     
         */
        public JPGridCoordinate getJPGridCoordinate() {
            return jpGridCoordinate;
        }

        /**
         * Sets the value of the jpGridCoordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link JPGridCoordinate }
         *     
         */
        public void setJPGridCoordinate(JPGridCoordinate value) {
            this.jpGridCoordinate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_MeshCode"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jpMeshCode"
    })
    public static class JPCoordinateMesh {

        @XmlElement(name = "JP_MeshCode", required = true)
        protected JPMeshCode jpMeshCode;

        /**
         * Gets the value of the jpMeshCode property.
         * 
         * @return
         *     possible object is
         *     {@link JPMeshCode }
         *     
         */
        public JPMeshCode getJPMeshCode() {
            return jpMeshCode;
        }

        /**
         * Sets the value of the jpMeshCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link JPMeshCode }
         *     
         */
        public void setJPMeshCode(JPMeshCode value) {
            this.jpMeshCode = value;
        }

    }

}
