//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JP_GridCoordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JP_GridCoordinate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JP_GridCoordinate.coordValues" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Sequence_Integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JP_GridCoordinate", propOrder = {
    "jpGridCoordinateCoordValues"
})
public class JPGridCoordinate {

    @XmlList
    @XmlElement(name = "JP_GridCoordinate.coordValues", namespace = "", required = true)
    protected List<BigInteger> jpGridCoordinateCoordValues;

    /**
     * Gets the value of the jpGridCoordinateCoordValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jpGridCoordinateCoordValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJPGridCoordinateCoordValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getJPGridCoordinateCoordValues() {
        if (jpGridCoordinateCoordValues == null) {
            jpGridCoordinateCoordValues = new ArrayList<BigInteger>();
        }
        return this.jpGridCoordinateCoordValues;
    }

}
