//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JP_RectifiedGrid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JP_RectifiedGrid">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Grid">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_RectifiedGrid.origin"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_RectifiedGrid.offsetVectors" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JP_RectifiedGrid", propOrder = {
    "jpRectifiedGridOrigin",
    "jpRectifiedGridOffsetVectors"
})
public class JPRectifiedGrid
    extends JPGrid
{

    @XmlElement(name = "JP_RectifiedGrid.origin", required = true)
    protected JPRectifiedGridOrigin jpRectifiedGridOrigin;
    @XmlElementRef(name = "JP_RectifiedGrid.offsetVectors", namespace = "http://www.gsi.go.jp/GIS/jpgis/standardSchemas", type = JAXBElement.class)
    protected List<JAXBElement<List<BigDecimal>>> jpRectifiedGridOffsetVectors;

    /**
     * Gets the value of the jpRectifiedGridOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link JPRectifiedGridOrigin }
     *     
     */
    public JPRectifiedGridOrigin getJPRectifiedGridOrigin() {
        return jpRectifiedGridOrigin;
    }

    /**
     * Sets the value of the jpRectifiedGridOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JPRectifiedGridOrigin }
     *     
     */
    public void setJPRectifiedGridOrigin(JPRectifiedGridOrigin value) {
        this.jpRectifiedGridOrigin = value;
    }

    /**
     * Gets the value of the jpRectifiedGridOffsetVectors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jpRectifiedGridOffsetVectors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJPRectifiedGridOffsetVectors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<List<BigDecimal>>> getJPRectifiedGridOffsetVectors() {
        if (jpRectifiedGridOffsetVectors == null) {
            jpRectifiedGridOffsetVectors = new ArrayList<JAXBElement<List<BigDecimal>>>();
        }
        return this.jpRectifiedGridOffsetVectors;
    }

}
