//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JP_RubberGrid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JP_RubberGrid">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_Grid">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_RubberGrid.gridCoords"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}JP_RubberGrid.groundPoints"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JP_RubberGrid", propOrder = {
    "jpRubberGridGridCoords",
    "jpRubberGridGroundPoints"
})
public class JPRubberGrid
    extends JPGrid
{

    @XmlElement(name = "JP_RubberGrid.gridCoords", required = true)
    protected SequenceJPCoordinate jpRubberGridGridCoords;
    @XmlElement(name = "JP_RubberGrid.groundPoints", required = true)
    protected SequenceGMPoint jpRubberGridGroundPoints;

    /**
     * Gets the value of the jpRubberGridGridCoords property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceJPCoordinate }
     *     
     */
    public SequenceJPCoordinate getJPRubberGridGridCoords() {
        return jpRubberGridGridCoords;
    }

    /**
     * Sets the value of the jpRubberGridGridCoords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceJPCoordinate }
     *     
     */
    public void setJPRubberGridGridCoords(SequenceJPCoordinate value) {
        this.jpRubberGridGridCoords = value;
    }

    /**
     * Gets the value of the jpRubberGridGroundPoints property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceGMPoint }
     *     
     */
    public SequenceGMPoint getJPRubberGridGroundPoints() {
        return jpRubberGridGroundPoints;
    }

    /**
     * Sets the value of the jpRubberGridGroundPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceGMPoint }
     *     
     */
    public void setJPRubberGridGroundPoints(SequenceGMPoint value) {
        this.jpRubberGridGroundPoints = value;
    }

}
