//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MD_Identifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MD_Identifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MD_Identifier.authority" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}ref_CI_Citation" minOccurs="0"/>
 *         &lt;element name="MD_Identifier.code" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MD_Identifier", propOrder = {
    "mdIdentifierAuthority",
    "mdIdentifierCode"
})
public class MDIdentifier {

    @XmlElement(name = "MD_Identifier.authority", namespace = "")
    protected RefCICitation mdIdentifierAuthority;
    @XmlElement(name = "MD_Identifier.code", namespace = "", required = true)
    protected String mdIdentifierCode;

    /**
     * Gets the value of the mdIdentifierAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link RefCICitation }
     *     
     */
    public RefCICitation getMDIdentifierAuthority() {
        return mdIdentifierAuthority;
    }

    /**
     * Sets the value of the mdIdentifierAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefCICitation }
     *     
     */
    public void setMDIdentifierAuthority(RefCICitation value) {
        this.mdIdentifierAuthority = value;
    }

    /**
     * Gets the value of the mdIdentifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMDIdentifierCode() {
        return mdIdentifierCode;
    }

    /**
     * Sets the value of the mdIdentifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMDIdentifierCode(String value) {
        this.mdIdentifierCode = value;
    }

}
