//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gsi.go.jp/GIS/jpgis/standardSchemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jp.canetrash.jpgis.stub;
