//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Record">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Record.attributes" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Record.recordType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Record", propOrder = {
    "recordAttributes",
    "recordRecordType"
})
public class Record
    extends IMObject
{

    @XmlElement(name = "Record.attributes", required = true)
    protected List<DictionaryAttributeNameAny> recordAttributes;
    @XmlElement(name = "Record.recordType", required = true)
    protected RefRecordType recordRecordType;

    /**
     * Gets the value of the recordAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DictionaryAttributeNameAny }
     * 
     * 
     */
    public List<DictionaryAttributeNameAny> getRecordAttributes() {
        if (recordAttributes == null) {
            recordAttributes = new ArrayList<DictionaryAttributeNameAny>();
        }
        return this.recordAttributes;
    }

    /**
     * Gets the value of the recordRecordType property.
     * 
     * @return
     *     possible object is
     *     {@link RefRecordType }
     *     
     */
    public RefRecordType getRecordRecordType() {
        return recordRecordType;
    }

    /**
     * Sets the value of the recordRecordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRecordType }
     *     
     */
    public void setRecordRecordType(RefRecordType value) {
        this.recordRecordType = value;
    }

}
