//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RS_LRS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RS_LRS">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}RS_ReferenceSystem">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}RS_LRS.domainOfValidity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}RS_LRS.theme"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}RS_LRS.overallOwner"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RS_LRS", propOrder = {
    "rslrsDomainOfValidity",
    "rslrsTheme",
    "rslrsOverallOwner"
})
public class RSLRS
    extends RSReferenceSystem
{

    @XmlElement(name = "RS_LRS.domainOfValidity")
    protected List<RefEXGeographicExtent> rslrsDomainOfValidity;
    @XmlElement(name = "RS_LRS.theme", required = true)
    protected String rslrsTheme;
    @XmlElement(name = "RS_LRS.overallOwner", required = true)
    protected RSLRSOverallOwner rslrsOverallOwner;

    /**
     * Gets the value of the rslrsDomainOfValidity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rslrsDomainOfValidity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRSLRSDomainOfValidity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefEXGeographicExtent }
     * 
     * 
     */
    public List<RefEXGeographicExtent> getRSLRSDomainOfValidity() {
        if (rslrsDomainOfValidity == null) {
            rslrsDomainOfValidity = new ArrayList<RefEXGeographicExtent>();
        }
        return this.rslrsDomainOfValidity;
    }

    /**
     * Gets the value of the rslrsTheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSLRSTheme() {
        return rslrsTheme;
    }

    /**
     * Sets the value of the rslrsTheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSLRSTheme(String value) {
        this.rslrsTheme = value;
    }

    /**
     * Gets the value of the rslrsOverallOwner property.
     * 
     * @return
     *     possible object is
     *     {@link RSLRSOverallOwner }
     *     
     */
    public RSLRSOverallOwner getRSLRSOverallOwner() {
        return rslrsOverallOwner;
    }

    /**
     * Sets the value of the rslrsOverallOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSLRSOverallOwner }
     *     
     */
    public void setRSLRSOverallOwner(RSLRSOverallOwner value) {
        this.rslrsOverallOwner = value;
    }

}
