//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SC_VerticalDatum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SC_VerticalDatum">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}IM_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}SC_VerticalDatum.datumID"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SC_VerticalDatum", propOrder = {
    "scVerticalDatumDatumID"
})
public class SCVerticalDatum
    extends IMObject
{

    @XmlElement(name = "SC_VerticalDatum.datumID", required = true)
    protected SCVerticalDatumDatumID scVerticalDatumDatumID;

    /**
     * Gets the value of the scVerticalDatumDatumID property.
     * 
     * @return
     *     possible object is
     *     {@link SCVerticalDatumDatumID }
     *     
     */
    public SCVerticalDatumDatumID getSCVerticalDatumDatumID() {
        return scVerticalDatumDatumID;
    }

    /**
     * Sets the value of the scVerticalDatumDatumID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCVerticalDatumDatumID }
     *     
     */
    public void setSCVerticalDatumDatumID(SCVerticalDatumDatumID value) {
        this.scVerticalDatumDatumID = value;
    }

}
