//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Set_GM_CurveSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Set_GM_CurveSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_LineString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}GM_Arc" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Set_GM_CurveSegment", propOrder = {
    "gmLineStringAndGMArc"
})
public class SetGMCurveSegment {

    @XmlElementRefs({
        @XmlElementRef(name = "GM_LineString", namespace = "http://www.gsi.go.jp/GIS/jpgis/standardSchemas", type = JAXBElement.class),
        @XmlElementRef(name = "GM_Arc", namespace = "http://www.gsi.go.jp/GIS/jpgis/standardSchemas", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends GMCurveSegments>> gmLineStringAndGMArc;

    /**
     * Gets the value of the gmLineStringAndGMArc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gmLineStringAndGMArc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGMLineStringAndGMArc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GMArc }{@code >}
     * {@link JAXBElement }{@code <}{@link GMLineString }{@code >}
     * {@link JAXBElement }{@code <}{@link GMCircle }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends GMCurveSegments>> getGMLineStringAndGMArc() {
        if (gmLineStringAndGMArc == null) {
            gmLineStringAndGMArc = new ArrayList<JAXBElement<? extends GMCurveSegments>>();
        }
        return this.gmLineStringAndGMArc;
    }

}
