//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_CalDate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_CalDate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_TemporalPosition">
 *       &lt;sequence>
 *         &lt;element name="TM_CalDate.calDate" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Sequence_Integer"/>
 *         &lt;element name="TM_CalDate.calendarEraName" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_CalDate", propOrder = {
    "tmCalDateCalDate",
    "tmCalDateCalendarEraName"
})
@XmlSeeAlso({
    TMDateAndTime.class
})
public class TMCalDate
    extends TMTemporalPosition
{

    @XmlList
    @XmlElement(name = "TM_CalDate.calDate", namespace = "", required = true)
    protected List<BigInteger> tmCalDateCalDate;
    @XmlElement(name = "TM_CalDate.calendarEraName", namespace = "", required = true)
    protected String tmCalDateCalendarEraName;

    /**
     * Gets the value of the tmCalDateCalDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmCalDateCalDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMCalDateCalDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getTMCalDateCalDate() {
        if (tmCalDateCalDate == null) {
            tmCalDateCalDate = new ArrayList<BigInteger>();
        }
        return this.tmCalDateCalDate;
    }

    /**
     * Gets the value of the tmCalDateCalendarEraName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMCalDateCalendarEraName() {
        return tmCalDateCalendarEraName;
    }

    /**
     * Sets the value of the tmCalDateCalendarEraName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMCalDateCalendarEraName(String value) {
        this.tmCalDateCalendarEraName = value;
    }

}
