//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_DateAndTime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_DateAndTime">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_CalDate">
 *       &lt;sequence>
 *         &lt;element name="TM_DateAndTime.clkTime" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Sequence_Number"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_DateAndTime", propOrder = {
    "tmDateAndTimeClkTime"
})
public class TMDateAndTime
    extends TMCalDate
{

    @XmlList
    @XmlElement(name = "TM_DateAndTime.clkTime", namespace = "", required = true)
    protected List<BigDecimal> tmDateAndTimeClkTime;

    /**
     * Gets the value of the tmDateAndTimeClkTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmDateAndTimeClkTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMDateAndTimeClkTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getTMDateAndTimeClkTime() {
        if (tmDateAndTimeClkTime == null) {
            tmDateAndTimeClkTime = new ArrayList<BigDecimal>();
        }
        return this.tmDateAndTimeClkTime;
    }

}
