//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_Edge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Edge">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_TopologicalPrimitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Edge.start"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Edge.end"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Edge.geometry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Edge", propOrder = {
    "tmEdgeStart",
    "tmEdgeEnd",
    "tmEdgeGeometry"
})
public class TMEdge
    extends TMTopologicalPrimitive
{

    @XmlElement(name = "TM_Edge.start", required = true)
    protected RefTMNode tmEdgeStart;
    @XmlElement(name = "TM_Edge.end", required = true)
    protected RefTMNode tmEdgeEnd;
    @XmlElement(name = "TM_Edge.geometry")
    protected RefTMPeriod tmEdgeGeometry;

    /**
     * Gets the value of the tmEdgeStart property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMNode }
     *     
     */
    public RefTMNode getTMEdgeStart() {
        return tmEdgeStart;
    }

    /**
     * Sets the value of the tmEdgeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMNode }
     *     
     */
    public void setTMEdgeStart(RefTMNode value) {
        this.tmEdgeStart = value;
    }

    /**
     * Gets the value of the tmEdgeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMNode }
     *     
     */
    public RefTMNode getTMEdgeEnd() {
        return tmEdgeEnd;
    }

    /**
     * Sets the value of the tmEdgeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMNode }
     *     
     */
    public void setTMEdgeEnd(RefTMNode value) {
        this.tmEdgeEnd = value;
    }

    /**
     * Gets the value of the tmEdgeGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMPeriod }
     *     
     */
    public RefTMPeriod getTMEdgeGeometry() {
        return tmEdgeGeometry;
    }

    /**
     * Sets the value of the tmEdgeGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMPeriod }
     *     
     */
    public void setTMEdgeGeometry(RefTMPeriod value) {
        this.tmEdgeGeometry = value;
    }

}
