//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_IndeterminateValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TM_IndeterminateValue">
 *   &lt;restriction base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}CharacterString">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="now"/>
 *     &lt;enumeration value="before"/>
 *     &lt;enumeration value="after"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TM_IndeterminateValue")
@XmlEnum
public enum TMIndeterminateValue {

    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("now")
    NOW("now"),
    @XmlEnumValue("before")
    BEFORE("before"),
    @XmlEnumValue("after")
    AFTER("after");
    private final String value;

    TMIndeterminateValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TMIndeterminateValue fromValue(String v) {
        for (TMIndeterminateValue c: TMIndeterminateValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
