//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_Instant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Instant">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_GeometricPrimitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Instant.position"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Instant.begunBy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Instant.endedBy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Instant.topology" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Instant", propOrder = {
    "tmInstantPosition",
    "tmInstantBegunBy",
    "tmInstantEndedBy",
    "tmInstantTopology"
})
public class TMInstant
    extends TMGeometricPrimitive
{

    @XmlElement(name = "TM_Instant.position", required = true)
    protected TMPosition tmInstantPosition;
    @XmlElement(name = "TM_Instant.begunBy")
    protected List<RefTMPeriod> tmInstantBegunBy;
    @XmlElement(name = "TM_Instant.endedBy")
    protected List<RefTMPeriod> tmInstantEndedBy;
    @XmlElement(name = "TM_Instant.topology")
    protected RefTMNode tmInstantTopology;

    /**
     * Gets the value of the tmInstantPosition property.
     * 
     * @return
     *     possible object is
     *     {@link TMPosition }
     *     
     */
    public TMPosition getTMInstantPosition() {
        return tmInstantPosition;
    }

    /**
     * Sets the value of the tmInstantPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMPosition }
     *     
     */
    public void setTMInstantPosition(TMPosition value) {
        this.tmInstantPosition = value;
    }

    /**
     * Gets the value of the tmInstantBegunBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmInstantBegunBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMInstantBegunBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefTMPeriod }
     * 
     * 
     */
    public List<RefTMPeriod> getTMInstantBegunBy() {
        if (tmInstantBegunBy == null) {
            tmInstantBegunBy = new ArrayList<RefTMPeriod>();
        }
        return this.tmInstantBegunBy;
    }

    /**
     * Gets the value of the tmInstantEndedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmInstantEndedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMInstantEndedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefTMPeriod }
     * 
     * 
     */
    public List<RefTMPeriod> getTMInstantEndedBy() {
        if (tmInstantEndedBy == null) {
            tmInstantEndedBy = new ArrayList<RefTMPeriod>();
        }
        return this.tmInstantEndedBy;
    }

    /**
     * Gets the value of the tmInstantTopology property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMNode }
     *     
     */
    public RefTMNode getTMInstantTopology() {
        return tmInstantTopology;
    }

    /**
     * Sets the value of the tmInstantTopology property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMNode }
     *     
     */
    public void setTMInstantTopology(RefTMNode value) {
        this.tmInstantTopology = value;
    }

}
