//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_Node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Node">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_TopologicalPrimitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Node.nextEdge" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Node.previousEdge" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Node.geometry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Node", propOrder = {
    "tmNodeNextEdge",
    "tmNodePreviousEdge",
    "tmNodeGeometry"
})
public class TMNode
    extends TMTopologicalPrimitive
{

    @XmlElement(name = "TM_Node.nextEdge")
    protected List<RefTMEdge> tmNodeNextEdge;
    @XmlElement(name = "TM_Node.previousEdge")
    protected List<RefTMEdge> tmNodePreviousEdge;
    @XmlElement(name = "TM_Node.geometry")
    protected RefTMInstant tmNodeGeometry;

    /**
     * Gets the value of the tmNodeNextEdge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmNodeNextEdge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMNodeNextEdge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefTMEdge }
     * 
     * 
     */
    public List<RefTMEdge> getTMNodeNextEdge() {
        if (tmNodeNextEdge == null) {
            tmNodeNextEdge = new ArrayList<RefTMEdge>();
        }
        return this.tmNodeNextEdge;
    }

    /**
     * Gets the value of the tmNodePreviousEdge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmNodePreviousEdge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMNodePreviousEdge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefTMEdge }
     * 
     * 
     */
    public List<RefTMEdge> getTMNodePreviousEdge() {
        if (tmNodePreviousEdge == null) {
            tmNodePreviousEdge = new ArrayList<RefTMEdge>();
        }
        return this.tmNodePreviousEdge;
    }

    /**
     * Gets the value of the tmNodeGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMInstant }
     *     
     */
    public RefTMInstant getTMNodeGeometry() {
        return tmNodeGeometry;
    }

    /**
     * Sets the value of the tmNodeGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMInstant }
     *     
     */
    public void setTMNodeGeometry(RefTMInstant value) {
        this.tmNodeGeometry = value;
    }

}
