//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_Period complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Period">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_GeometricPrimitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Period.begin"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Period.end"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Period.topology" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Period", propOrder = {
    "tmPeriodBegin",
    "tmPeriodEnd",
    "tmPeriodTopology"
})
public class TMPeriod
    extends TMGeometricPrimitive
{

    @XmlElement(name = "TM_Period.begin", required = true)
    protected RefTMInstant tmPeriodBegin;
    @XmlElement(name = "TM_Period.end", required = true)
    protected RefTMInstant tmPeriodEnd;
    @XmlElement(name = "TM_Period.topology")
    protected RefTMEdge tmPeriodTopology;

    /**
     * Gets the value of the tmPeriodBegin property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMInstant }
     *     
     */
    public RefTMInstant getTMPeriodBegin() {
        return tmPeriodBegin;
    }

    /**
     * Sets the value of the tmPeriodBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMInstant }
     *     
     */
    public void setTMPeriodBegin(RefTMInstant value) {
        this.tmPeriodBegin = value;
    }

    /**
     * Gets the value of the tmPeriodEnd property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMInstant }
     *     
     */
    public RefTMInstant getTMPeriodEnd() {
        return tmPeriodEnd;
    }

    /**
     * Sets the value of the tmPeriodEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMInstant }
     *     
     */
    public void setTMPeriodEnd(RefTMInstant value) {
        this.tmPeriodEnd = value;
    }

    /**
     * Gets the value of the tmPeriodTopology property.
     * 
     * @return
     *     possible object is
     *     {@link RefTMEdge }
     *     
     */
    public RefTMEdge getTMPeriodTopology() {
        return tmPeriodTopology;
    }

    /**
     * Sets the value of the tmPeriodTopology property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTMEdge }
     *     
     */
    public void setTMPeriodTopology(RefTMEdge value) {
        this.tmPeriodTopology = value;
    }

}
