//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TM_Position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_Position.anyOther"/>
 *         &lt;element name="date8601" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Date"/>
 *         &lt;element name="time8601" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}Time"/>
 *         &lt;element name="datetime8601" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}DateTime"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Position", propOrder = {
    "tmPositionAnyOther",
    "date8601",
    "time8601",
    "datetime8601"
})
public class TMPosition {

    @XmlElement(name = "TM_Position.anyOther")
    protected TMPositionAnyOther tmPositionAnyOther;
    @XmlElement(namespace = "")
    protected XMLGregorianCalendar date8601;
    @XmlElement(namespace = "")
    protected XMLGregorianCalendar time8601;
    @XmlElement(namespace = "")
    protected XMLGregorianCalendar datetime8601;

    /**
     * Gets the value of the tmPositionAnyOther property.
     * 
     * @return
     *     possible object is
     *     {@link TMPositionAnyOther }
     *     
     */
    public TMPositionAnyOther getTMPositionAnyOther() {
        return tmPositionAnyOther;
    }

    /**
     * Sets the value of the tmPositionAnyOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMPositionAnyOther }
     *     
     */
    public void setTMPositionAnyOther(TMPositionAnyOther value) {
        this.tmPositionAnyOther = value;
    }

    /**
     * Gets the value of the date8601 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate8601() {
        return date8601;
    }

    /**
     * Sets the value of the date8601 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate8601(XMLGregorianCalendar value) {
        this.date8601 = value;
    }

    /**
     * Gets the value of the time8601 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime8601() {
        return time8601;
    }

    /**
     * Sets the value of the time8601 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime8601(XMLGregorianCalendar value) {
        this.time8601 = value;
    }

    /**
     * Gets the value of the datetime8601 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetime8601() {
        return datetime8601;
    }

    /**
     * Sets the value of the datetime8601 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetime8601(XMLGregorianCalendar value) {
        this.datetime8601 = value;
    }

}
