//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_TemporalPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_TemporalPosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TM_TemporalPosition.indeterminatePosition" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TM_IndeterminateValue" minOccurs="0"/>
 *         &lt;element name="TM_TemporalPosition.frame" type="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}ref_RS_CRS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_TemporalPosition", propOrder = {
    "tmTemporalPositionIndeterminatePosition",
    "tmTemporalPositionFrame"
})
@XmlSeeAlso({
    TMCalDate.class
})
public class TMTemporalPosition {

    @XmlElement(name = "TM_TemporalPosition.indeterminatePosition", namespace = "")
    protected TMIndeterminateValue tmTemporalPositionIndeterminatePosition;
    @XmlElement(name = "TM_TemporalPosition.frame", namespace = "")
    protected RefRSCRS tmTemporalPositionFrame;

    /**
     * Gets the value of the tmTemporalPositionIndeterminatePosition property.
     * 
     * @return
     *     possible object is
     *     {@link TMIndeterminateValue }
     *     
     */
    public TMIndeterminateValue getTMTemporalPositionIndeterminatePosition() {
        return tmTemporalPositionIndeterminatePosition;
    }

    /**
     * Sets the value of the tmTemporalPositionIndeterminatePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMIndeterminateValue }
     *     
     */
    public void setTMTemporalPositionIndeterminatePosition(TMIndeterminateValue value) {
        this.tmTemporalPositionIndeterminatePosition = value;
    }

    /**
     * Gets the value of the tmTemporalPositionFrame property.
     * 
     * @return
     *     possible object is
     *     {@link RefRSCRS }
     *     
     */
    public RefRSCRS getTMTemporalPositionFrame() {
        return tmTemporalPositionFrame;
    }

    /**
     * Sets the value of the tmTemporalPositionFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefRSCRS }
     *     
     */
    public void setTMTemporalPositionFrame(RefRSCRS value) {
        this.tmTemporalPositionFrame = value;
    }

}
