//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 Œß‘O JST 
//


package jp.canetrash.jpgis.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TP_DirectedTopo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TP_DirectedTopo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TP_Primitive">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TP_DirectedTopo.orientation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TP_DirectedTopo", propOrder = {
    "tpDirectedTopoOrientation"
})
@XmlSeeAlso({
    TPDirectedNode.class,
    TPDirectedFace.class,
    TPDirectedEdge.class
})
public abstract class TPDirectedTopo
    extends TPPrimitive
{

    @XmlElement(name = "TP_DirectedTopo.orientation", required = true)
    protected String tpDirectedTopoOrientation;

    /**
     * Gets the value of the tpDirectedTopoOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPDirectedTopoOrientation() {
        return tpDirectedTopoOrientation;
    }

    /**
     * Sets the value of the tpDirectedTopoOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPDirectedTopoOrientation(String value) {
        this.tpDirectedTopoOrientation = value;
    }

}
