//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 01:19:58 午前 JST 
//


package jp.canetrash.jpgis.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * JPGIS7.3.3.1ではTP_Primitiveの合成関連proxyの多重度は「2」としているが（原規格に準拠），この状態で実装するとデータがループするため，これを回避するためにXML Schemaでは多重度を「0..2」とする。
 * 
 * <p>Java class for TP_Primitive complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TP_Primitive">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TP_Object">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TP_Primitive.complex" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.gsi.go.jp/GIS/jpgis/standardSchemas}TP_Primitive.proxy" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TP_Primitive", propOrder = {
    "tpPrimitiveComplex",
    "tpPrimitiveProxy"
})
@XmlSeeAlso({
    TPDirectedTopo.class
})
public abstract class TPPrimitive
    extends TPObject
{

    @XmlElement(name = "TP_Primitive.complex", required = true)
    protected List<IMObjectReference> tpPrimitiveComplex;
    @XmlElement(name = "TP_Primitive.proxy")
    protected List<TPPrimitiveProxy> tpPrimitiveProxy;

    /**
     * Gets the value of the tpPrimitiveComplex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tpPrimitiveComplex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTPPrimitiveComplex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IMObjectReference }
     * 
     * 
     */
    public List<IMObjectReference> getTPPrimitiveComplex() {
        if (tpPrimitiveComplex == null) {
            tpPrimitiveComplex = new ArrayList<IMObjectReference>();
        }
        return this.tpPrimitiveComplex;
    }

    /**
     * Gets the value of the tpPrimitiveProxy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tpPrimitiveProxy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTPPrimitiveProxy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPPrimitiveProxy }
     * 
     * 
     */
    public List<TPPrimitiveProxy> getTPPrimitiveProxy() {
        if (tpPrimitiveProxy == null) {
            tpPrimitiveProxy = new ArrayList<TPPrimitiveProxy>();
        }
        return this.tpPrimitiveProxy;
    }

}
