INSERT INTO DEPARTMENT (CODE, DPTNAME) VALUES ('A01', 'Development');
INSERT INTO DEPARTMENT (CODE, DPTNAME) VALUES ('A02', 'Research');
INSERT INTO DEPARTMENT (CODE, DPTNAME) VALUES ('B01', 'Sales');
INSERT INTO DEPARTMENT (CODE, DPTNAME) VALUES ('C01', 'Accounting');

INSERT INTO EMPLOYEE ( ID, NAME, DPTCODE ) VALUES ( 1, 'John', 'A01');
INSERT INTO EMPLOYEE ( ID, NAME, DPTCODE ) VALUES ( 2, 'Elvin', 'A02');
INSERT INTO EMPLOYEE ( ID, NAME, DPTCODE ) VALUES ( 3, 'McCoy', 'C01');
INSERT INTO EMPLOYEE ( ID, NAME, DPTCODE ) VALUES ( 4, 'Richard', 'A02');
INSERT INTO EMPLOYEE ( ID, NAME, DPTCODE ) VALUES ( 5, 'Eric', 'B01');

